spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2b8
    username: root
    password: root

    #     Failed to start bean 'documentationPluginsBootstrapper';
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  ip: 116.62.41.153
  port: 9090

mybatis:
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 自定义
files:
  upload:
    path: /root/files/